addr = "192.168.17.133:3306"
user = "root"
password = "123456"
charset = "utf8"
server_id = 2001
flavor = "mysql"
heartbeat_period = 0
read_timeout = 0
include_table_regex = []
exclude_table_regex = []
discard_no_meta_row_event = false
use_decimal = false
parse_time = false
semi_sync_enabled = false
max_reconnect_attempts = 0
[dump]
    mysqldump = "mysqldump"
    tables = ["ztest"]
    table_db = "diss2_test"
    dbs = []
    ignore_tables = []
    where = ""
    discard_err = true
    skip_master_data = false
    max_allowed_packet_mb = 0
    protocol = ""

	